import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientCookiesProvider from "@/components/CookiesProvider";
import { getCookies } from "next-client-cookies/server";

import { cookies } from "next/headers";

import { defaultTheme } from "@/lib/themes";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = getCookies().get("theme");

  return (
    <html data-theme={theme || defaultTheme} lang="it">
      <ClientCookiesProvider value={cookies().getAll()}>
        <body className={inter.className + " min-h-[100vh]"}>
          <Navbar />

          {children}
        </body>
      </ClientCookiesProvider>
    </html>
  );
}
